# Change these first
owner: SoftwareDeveloper2002  # Your GitHub organization or username
repo: upper                   # The name of this repository

sites:
  - name: rtechonn
    url: https://crmbackend-6ka4.onrender.com

status-website:
  # Use your custom domain if you have one
  # Base URL for GitHub Pages
  baseUrl: /upper
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: >
    This status page shows **real-time** data from our [GitHub repository](https://github.com/SoftwareDeveloper2002/upper). 
    No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/SoftwareDeveloper2002/upper

# Optional notifications when a site goes down
notifications:
  - type: email
    recipients:
      - robbyroda.00@gmail.com

# Automatically create GitHub issues when downtime is detected
issues:
  create: true
  labels:
    - outage
